version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "pytest --maxfail=1 --disable-warnings && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
